### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by LouisAmon** [nuage-studio/lambda-package#2]
Reading the .gitignore is not necessarily what everyone wants for their Lambda packaging (cf. #1)

Instead, I suggest we use the standards and have a configuration file in TOML language (like pylint with its .pylintrc or .flake8)

We could create a `.lambda-packagingrc` (it's a bit verbose but I'm trying to avoid namespace collisions with "packaging" with is a Pip library and "package" which is a generic python term)

The file could also not be used and instead one could use the standard `setup.cfg` (flake8 does that as well)

Regarding the configuration itself, I think a list of parameter could be:

- [ ] output (dry run if not set) : where to put the zip of the Lambda
- [ ] exclude : a list of .gitignore-style glob patterns that should not be in the package

The following extra params will be discussed in #3:

- [ ] requirements : path to the requirements.txt file (if not set the dependencies are not packaged)
- [ ] layer-output : wether the requirements should be in the lambda package directly or in a separate output, and where this output should be
- [ ] use-docker (defaults to true) : wether the Layer should be compiled via a docker image
- [ ] python-version (defaults to the python -V) : which Python version to use via Docker to package the requirements

**Comment by cloudspeak** [comment]
Hi Louis, I have a quick question:

>  use-docker (defaults to true) : wether the Layer should be compiled via a docker image

If `use-docker` is false, how should this work?  Do we simply run the same `pip` command but on the local machine instead of docker?

**Comment by LouisAmon** [comment]
Yeah, that was the idea

To be honest it may be a bit redundant because a good Lambda should be packaged with Lambda, but for those people using CentOS or AmazonLinux VMs directly (e.g. in a CI) : they may not want to bother with docker
